export enum ErrorType {
  VALIDATION_ERROR = "VALIDATION ERROR",
  INVALID_REQUEST_BODY = "INVALID REQUEST BODY",
  UNKNOWN_ERROR = "UNKNOWN ERROR",
  FIELD_NOT_EXIST = "MISSING FIELD",
  INVALID_TYPE = "INVALID TYPE"
}